# Generated by Django 4.2.4 on 2023-10-16 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False)),
                ('fullName', models.CharField(blank=True, max_length=100, null=True, verbose_name='Полное имя')),
                ('phone', models.PositiveIntegerField(blank=True, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Город')),
                ('deliveryType', models.CharField(default='paid', max_length=30)),
                ('paymentType', models.CharField(default='online', max_length=30)),
                ('status', models.CharField(default='accepted', max_length=30)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('updated', models.BooleanField(default=True)),
                ('totalCost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена заказа')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
